[package]
name = "poltergeist"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
glam = "0.23.0"
manifest-dir-macros = "0.1.16"
mint = "0.5.9"
rustc-hash = "1.1.0"
stardust-xr-fusion = "0.38.1"
stardust-xr-molecules = "0.21.1"
tokio = "1.24.2"